TRAINING_WINDOW_DAYS = 365
TRAINING_LOOKBACK_DAYS = 180
PREDICTION_CENSOR_HOURS = 24

# Reused Col Names
HOURS_TO_CANCEL_COL = 'GROSS_ADD__HOURS_TO_CANCEL'
# General Col Categories
TIME_COL = 'GROSS_ADD__CREATED'
TARGET_COL = 'NET_BILLINGS'
PASSTHROUGH_COLS = [
    'GROSS_ADD',
    'GROSS_ADD__CREATED',
    HOURS_TO_CANCEL_COL,
    'EMAIL',
    'PHONE',
    'GCLID',
]
TARGET_ENCODE_COLS = [
    'BIN_ISSUING_BANK',
    'CAMPAIGN',
    'CONNECTION_ISP',
    'TRAFFIC_SOURCE',
    'CARD_NETWORK_SUBTYPE',
]
CAT_COLS = [
    'BRAND',
    'GROSS_ADD__TYPE',
    'GROSS_ADD__LEVEL',
    'CHANNEL',
    'DEVICE_OS_NAME',
    'CONNECTION_USER_TYPE',
    'CONNECTION_TYPE',
    'PAYMENT_TYPE',
    'CARD_NETWORK',
    'BIN_AFFLUENCE',
    'BIN_ISSUER_COUNTRY',
    'BIN_FUNDING_SOURCE',
    'BIN_CORPORATE',
    'BIN_PREPAID_TYPE',
    'BIN_RELOADABLE',
    'AVS_RESULT_TYPE',
    'MAIN_ITEM',
    'OFFER_TYPE',
]
NUM_COLS = [
    # 'BIRTH_YEAR',
    'MEDIAN_HOUSEHOLD_INCOME',
    'PER_CAPITA_INCOME',
    'MEDIAN_HOME_VALUE',
    'POVERTY_RATE',
    'UNEMPLOYMENT_RATE',
    'PROMO_DAYS',
    'PROMO_PRICE',
    'RECURRING_DAYS',
    'RECURRING_PRICE',
    'ANNUAL_RECURRING_PRICE',
    'DAY_ONE_REPORT_VIEWS',
    'DAY_ONE_SELF_SEARCH_REPORT_VIEWS',
    'DAY_ONE_FAMILY_REPORT_VIEWS',
    'CROSS_SELL_ADDS',
]
BOOLEAN_COLS = [
    # 'DEVICE_IS_MOBILE',
    'DEVICE_IS_OS_APPLE',
    'DEVICE_IS_OS_ANDROID',
    'CONNECTION_IS_ANONYMOUS',
    'HAS_CARD_DATA',
    'IS_PREPAID',
    'IS_PROMO',
    'HAS_DAY_ONE_REPORT_VIEW',
    'HAS_DAY_ONE_SELF_SEARCH_REPORT_VIEW',
    'HAS_DAY_ONE_FAMILY_REPORT_VIEW',
    'HAS_CROSS_SELL',
]
XGBOOST_PARAMS = {
    'n_estimators': 300,
    'max_depth': 8,
    'learning_rate': 0.05,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'random_state': 42,
}
TRAINING_COLS = CAT_COLS + NUM_COLS + BOOLEAN_COLS + TARGET_ENCODE_COLS
ALL_COLS = PASSTHROUGH_COLS + [TIME_COL] + [TARGET_COL] + TRAINING_COLS