-- Using Snowflake VS Code Extension login to account vx70256-sw09563 - Signle Sign On
SET MY_USER_NAME = 'ML_LAYER_USER';
SET MY_ROLE_NAME = 'ML_LAYER_ROLE';
SET MY_DB_NAME = 'ML_LAYER_DB';
SET MY_WH_NAME = 'ML_LAYER_WH';
SET ADMIN_ROLE = 'ACCOUNTADMIN';
SET MY_NETWORK_POLICY_NAME = 'ML_LAYER_NETWORK_POLICY';

-- 1. Context Setup
USE ROLE IDENTIFIER($ADMIN_ROLE);

-- 2. Create Role
CREATE OR REPLACE ROLE IDENTIFIER($MY_ROLE_NAME);
GRANT ROLE IDENTIFIER($MY_ROLE_NAME) TO ROLE SYSADMIN;

-- 3. Create Warehouse
CREATE OR REPLACE WAREHOUSE IDENTIFIER($MY_WH_NAME)
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for ML Snowpark workloads';

GRANT USAGE ON WAREHOUSE IDENTIFIER($MY_WH_NAME) TO ROLE IDENTIFIER($MY_ROLE_NAME);
GRANT OPERATE ON WAREHOUSE IDENTIFIER($MY_WH_NAME) TO ROLE IDENTIFIER($MY_ROLE_NAME);

-- 4. Create Database
CREATE OR REPLACE DATABASE IDENTIFIER($MY_DB_NAME);
GRANT OWNERSHIP ON DATABASE IDENTIFIER($MY_DB_NAME) TO ROLE IDENTIFIER($MY_ROLE_NAME) COPY CURRENT GRANTS;

-- 5. Create User
CREATE OR REPLACE USER IDENTIFIER($MY_USER_NAME)
    PASSWORD = 'ChangeMe123!'
    DEFAULT_ROLE = $MY_ROLE_NAME
    DEFAULT_WAREHOUSE = $MY_WH_NAME
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service user for ML operations';

-- 6. Grant Role to User
GRANT ROLE IDENTIFIER($MY_ROLE_NAME) TO USER IDENTIFIER($MY_USER_NAME);

-- 7. Network Policy
CREATE OR REPLACE NETWORK POLICY ML_LAYER_NETWORK_POLICY
    ALLOWED_IP_LIST = ('99.39.71.201');

ALTER USER IDENTIFIER($MY_USER_NAME) UNSET NETWORK_POLICY;
ALTER USER IDENTIFIER($MY_USER_NAME) SET NETWORK_POLICY = $MY_NETWORK_POLICY_NAME;

-- Final check
SELECT 
    $MY_DB_NAME as database, 
    $MY_WH_NAME as warehouse, 
    $MY_ROLE_NAME as role, 
    $MY_USER_NAME as user,
    'Setup Complete - NOW RUN setup/setup_key_pair.sql' as status;
